import { Weather, getConditionEmoji } from "../services/weather.service";

const escapeHtml = (value: string): string =>
  value.replace(/[&<>"']/g, (char) => {
    const entities: Record<string, string> = {
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;",
    };
    return entities[char];
  });

const renderCard = (weather: Weather): string => {
  const city = escapeHtml(weather.city);
  const emoji = getConditionEmoji(weather.condition);
  return `
    <article class="card">
      <h2 class="city">${city}</h2>
      <div class="emoji" aria-hidden="true">${emoji}</div>
      <div class="temp">${weather.temp}°C</div>
      <div class="condition">${escapeHtml(weather.condition)}</div>
      <div class="humidity">💧 ${weather.humidity}% humidity</div>
    </article>
  `;
};

export const renderDashboard = (cities: Weather[]): string => `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Weather Dashboard</title>
  <style>
    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      min-height: 100vh;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      background: linear-gradient(135deg, #1e3c72 0%, #2a5298 50%, #4facfe 100%);
      padding: 3rem 1.5rem;
      color: #1a1a2e;
    }

    header {
      text-align: center;
      margin-bottom: 2.5rem;
      color: #ffffff;
    }

    header h1 {
      font-size: 2.5rem;
      font-weight: 700;
      text-shadow: 0 2px 8px rgba(0, 0, 0, 0.2);
    }

    header p {
      margin-top: 0.5rem;
      font-size: 1rem;
      opacity: 0.85;
    }

    .grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
      gap: 1.5rem;
      max-width: 1100px;
      margin: 0 auto;
    }

    .card {
      background: rgba(255, 255, 255, 0.95);
      border-radius: 16px;
      padding: 1.75rem 1.25rem;
      text-align: center;
      box-shadow: 0 10px 30px rgba(0, 0, 0, 0.15);
      transition: transform 0.2s ease, box-shadow 0.2s ease;
    }

    .card:hover {
      transform: translateY(-6px);
      box-shadow: 0 16px 36px rgba(0, 0, 0, 0.22);
    }

    .city {
      font-size: 1.25rem;
      font-weight: 600;
      text-transform: capitalize;
      margin-bottom: 0.5rem;
      color: #1e3c72;
    }

    .emoji {
      font-size: 3rem;
      line-height: 1;
      margin: 0.5rem 0;
    }

    .temp {
      font-size: 2.25rem;
      font-weight: 700;
      color: #1a1a2e;
    }

    .condition {
      margin-top: 0.25rem;
      font-size: 1rem;
      color: #555;
    }

    .humidity {
      margin-top: 0.75rem;
      font-size: 0.9rem;
      color: #2a5298;
      font-weight: 500;
    }

    footer {
      text-align: center;
      margin-top: 2.5rem;
      color: rgba(255, 255, 255, 0.75);
      font-size: 0.85rem;
    }
  </style>
</head>
<body>
  <header>
    <h1>🌤️ Weather Dashboard</h1>
    <p>Current conditions across the globe</p>
  </header>

  <main class="grid">
    ${cities.map(renderCard).join("")}
  </main>

  <footer>
    <p>Mock data · generated by Weather API</p>
  </footer>
</body>
</html>
`;
